---
# Source: python-producer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-python-producer
  labels:
    helm.sh/chart: python-producer-0.1.0
    app.kubernetes.io/name: python-producer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
---
# Source: python-producer/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-python-producer
  labels:
    helm.sh/chart: python-producer-0.1.0
    app.kubernetes.io/name: python-producer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: python-producer
    app.kubernetes.io/instance: release-name
---
# Source: python-producer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-python-producer
  labels:
    helm.sh/chart: python-producer-0.1.0
    app.kubernetes.io/name: python-producer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: python-producer
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: python-producer
        app.kubernetes.io/instance: release-name
    spec:
      serviceAccountName: release-name-python-producer
      securityContext:
        {}
      restartPolicy: Always
      containers:
        - name: python-producer
          securityContext:
            {}
          image: "emrede/python-producer:latest"
          imagePullPolicy: IfNotPresent
          
          # command: ["python3", "-u", "send.py"]
          # command: [ "sleep" ]
          # args: [ "infinity" ]
          # ports:
          #   - name: http
          #     containerPort: 80
          #     protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     initialDelaySeconds: 30
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #     initialDelaySeconds: 30
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
# Source: python-producer/templates/tests/test-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-python-producer-test-connection"
  labels:
    helm.sh/chart: python-producer-0.1.0
    app.kubernetes.io/name: python-producer
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": test
spec:
  containers:
    - name: wget
      image: busybox
      command: ['wget']
      args: ['release-name-python-producer:80']
  restartPolicy: Never
